[package]
name = "blink-stm32l4"
version = "0.1.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
description = """
Example program for STM32L4 using Drone RTOS.
"""
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/valff/blink-stm32l4"

[dependencies]
clippy = {version = "*", optional = true}

[dependencies.drone]
version = "0.2"

[dependencies.drone-stm32]
version = "0.2"
features = ["stm32l4x6"]

[dev-dependencies.test]
version = "0.2"
features = []
git = "https://github.com/valff/drone-test"

[lib]

[[bin]]
name = "blink-stm32l4"
test = false
doc = false

[profile.dev]
opt-level = 3
lto = true
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"

[profile.test]
panic = "abort"

[profile.bench]
opt-level = 3
lto = true
panic = "abort"

[profile.doc]
opt-level = 3
lto = true
panic = "abort"
