[package]
name = "blink-nucleo"
version = "0.1.0"
authors = ["Valentine Valyaeff <valentine.valyaeff@gmail.com>"]
description = "Example program for STM32 Nucleo using Drone RTOS."
readme = "README.md"
license = "MIT/Apache-2.0"
repository = "https://github.com/drone-os/blink-nucleo"

[dependencies.drone]
version = "0.6"

[dependencies.drone-cortex-m]
version = "0.6"
features = ["stm32l4x6"]

[dependencies.futures]
version = "0.1"
default-features = false

[dependencies.clippy]
version = "*"
optional = true

[dev-dependencies.test]
version = "0.2"
features = []
git = "https://github.com/drone-os/drone-test"

[[bin]]
name = "blink-nucleo"
path = "src/main.rs"
test = false
doc = false

[profile.dev]
panic = "abort"

[profile.release]
opt-level = 3
lto = true
panic = "abort"

[profile.test]
panic = "abort"

[profile.bench]
opt-level = 3
lto = true
panic = "abort"

[profile.doc]
panic = "abort"
